dependencies:
  flutter:
    sdk: flutter
  socket_io_client: ^2.0.0
  provider: ^6.0.0
  device_info_plus: ^9.0.0
  image_picker: ^1.0.4
  video_player: ^2.8.1
  path_provider: ^2.1.1
  flutter_background_service: ^5.0.0
  flutter_local_notifications: ^17.0.0
  permission_handler: ^11.0.0