name: spatial_flow_client
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

# --- ADD THIS SECTION ---
environment:
  sdk: '>=3.2.0 <4.0.0'
# ------------------------
dependencies:
  flutter:
    sdk: flutter
  # Core Logic
  provider: ^6.0.0
  socket_io_client: ^2.0.0
  device_info_plus: ^9.0.0
  
  # Media & Files
  video_player: ^2.7.0
  image_picker: ^1.0.0
  path_provider: ^2.1.2
  open_filex: ^4.3.2         # Opens files on tap
  gal: ^2.2.0                # Save to Gallery (Visible)
  permission_handler: ^11.0.0
  
  # System & UI
  wakelock_plus: ^1.1.0      # Keeps screen alive
  desktop_drop: ^0.4.4       # Drag from Windows Explorer
  flutter_background_service: ^5.0.0 # Keep Android Alive
  flutter_local_notifications: ^17.0.0

  # ... other deps ...
  video_thumbnail: ^0.5.3  # <--- NEW: For Video Holograms
  flutter_image_compress: ^2.1.0








