name: spatial_flow_client
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

# --- ADD THIS SECTION ---
environment:
  sdk: '>=3.2.0 <4.0.0'
# ------------------------
dependencies:
  flutter:
    sdk: flutter
  socket_io_client: ^2.0.0
  provider: ^6.0.0
  device_info_plus: ^9.0.0
  image_picker: ^1.0.4
  video_player: ^2.8.1
  path_provider: ^2.1.2
  flutter_background_service: ^5.0.0
  flutter_local_notifications: ^17.0.0
  wakelock_plus: ^1.1.0  # <--- KEEPS CONNECTION ALIVE
  open_filex: ^4.3.2     # <--- OPENS FILES ON CLICK
  permission_handler: ^11.0.0
  desktop_drop: ^0.4.4           # Drag from Windows Explorer
  gal: ^2.2.0                    # Save to Gallery (Visible)
  flutter_background_service: ^5.0.0 # Keep Android Alive
  




